# Release task for Akka.Streams.Kafka
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

trigger:
  branches:
    include:
      - refs/tags/*
pr: none

variables:
  - group: nugetKeys
  - name: githubConnectionName
    value: AkkaDotNet_Releases
  - name: projectName
    value: Akka.Streams.Kafka
  - name: githubRepositoryName
    value: akkadotnet/Akka.Streams.Kafka

jobs:
  - job: Release
    pool:
      vmImage: windows-latest
      demands: Cmd
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET SDK from global.json'
        inputs:
          useGlobalJson: true
          
      - powershell: ./build.ps1
        displayName: 'Update Release Notes'

      # Pack without version suffix for release
      - script: dotnet pack -c Release -o $(Build.ArtifactStagingDirectory)/nuget
        displayName: 'Create packages'

      - script: dotnet nuget push "$(Build.ArtifactStagingDirectory)\nuget\*.nupkg" --api-key $(nugetKey) --source https://api.nuget.org/v3/index.json --skip-duplicate
        displayName: 'Publish to NuGet.org'

      - task: GitHubRelease@0
        displayName: 'GitHub release (create)'
        inputs:
          gitHubConnection: $(githubConnectionName)
          repositoryName: $(githubRepositoryName)
          title: '$(projectName) v$(Build.SourceBranchName)'
          releaseNotesFile: 'RELEASE_NOTES.md'
          assets: '$(Build.ArtifactStagingDirectory)/nuget/*.nupkg'
