name: Publish NuGet

on:
  push:
    tags:
      - '*'

jobs:
  publish-nuget:

    name: publish-nuget
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4.2.2
      with:
        lfs: true
        fetch-depth: 0
        
    - name: "Install .NET SDK"
      uses: actions/setup-dotnet@v4.3.1
      with:
        global-json-file: "./global.json"

    - name: "Restore .NET tools"
      run: dotnet tool restore

    - name: "Update release notes"
      shell: pwsh
      run: |
        ./build.ps1

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: 'mssql-mcp ${{ github.ref_name }}'
        tag_name: ${{ github.ref }}
        body_path: RELEASE_NOTES.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

   # - name: Upload Release Asset
   #   uses: AButler/upload-release-assets@v3.0
   #   with:
   #       repo-token: ${{ github.token }}
   #       release-tag: ${{ github.ref_name }}
   #       files: 'output/*.nupkg'
